package Giza.Hershey_Fonts.Markers is
   Font : constant Giza.Font.Ref_Const;
private
   Glyph_0 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_1 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_2 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_3 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_4 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_5 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_6 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_7 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_8 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_9 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_10 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_11 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_12 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_13 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_14 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_15 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_16 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_17 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_18 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_19 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_20 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_21 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_22 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_23 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_24 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_25 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_26 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_27 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_28 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_29 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_30 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_31 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_32 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_33 : aliased constant Glyph :=
     (Number_Of_Vectors => 18,
      Width => 14,
      Height => 14,
      Y_Offset => -7,
      X_Offset => -7,
      Vects => (Raise_Pen,
(-1, -7),
(-4, -6),
(-6, -4),
(-7, -1),
(-7, 1),
(-6, 4),
(-4, 6),
(-1, 7),
(1, 7),
(4, 6),
(6, 4),
(7, 1),
(7, -1),
(6, -4),
(4, -6),
(1, -7),
(-1, -7)));
   Glyph_34 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 12,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-6, -6),
(-6, 6),
(6, 6),
(6, -6),
(-6, -6)));
   Glyph_35 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Width => 14,
      Height => 12,
      Y_Offset => -8,
      X_Offset => -7,
      Vects => (Raise_Pen,
(0, -8),
(-7, 4),
(7, 4),
(0, -8)));
   Glyph_36 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 12,
      Height => 20,
      Y_Offset => -10,
      X_Offset => -6,
      Vects => (Raise_Pen,
(0, -10),
(-6, 0),
(0, 10),
(6, 0),
(0, -10)));
   Glyph_37 : aliased constant Glyph :=
     (Number_Of_Vectors => 12,
      Width => 16,
      Height => 16,
      Y_Offset => -9,
      X_Offset => -8,
      Vects => (Raise_Pen,
(0, -9),
(-2, -3),
(-8, -3),
(-3, 1),
(-5, 7),
(0, 3),
(5, 7),
(3, 1),
(8, -3),
(2, -3),
(0, -9)));
   Glyph_38 : aliased constant Glyph :=
     (Number_Of_Vectors => 14,
      Width => 12,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-2, -6),
(-2, -2),
(-6, -2),
(-6, 2),
(-2, 2),
(-2, 6),
(2, 6),
(2, 2),
(6, 2),
(6, -2),
(2, -2),
(2, -6),
(-2, -6)));
   Glyph_39 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 14,
      Height => 14,
      Y_Offset => -7,
      X_Offset => -7,
      Vects => (Raise_Pen,
(0, -7),
(0, 7),
Raise_Pen,
(-7, 0),
(7, 0)));
   Glyph_40 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 10,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -5,
      Vects => (Raise_Pen,
(-5, -5),
(5, 5),
Raise_Pen,
(5, -5),
(-5, 5)));
   Glyph_41 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Width => 10,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, -6),
(0, 6),
Raise_Pen,
(-5, -3),
(5, 3),
Raise_Pen,
(5, -3),
(-5, 3)));
   Glyph_42 : aliased constant Glyph :=
     (Number_Of_Vectors => 35,
      Width => 8,
      Height => 8,
      Y_Offset => -4,
      X_Offset => -4,
      Vects => (Raise_Pen,
(-1, -4),
(-3, -3),
(-4, -1),
(-4, 1),
(-3, 3),
(-1, 4),
(1, 4),
(3, 3),
(4, 1),
(4, -1),
(3, -3),
(1, -4),
(-1, -4),
Raise_Pen,
(-3, -1),
(-3, 1),
Raise_Pen,
(-2, -2),
(-2, 2),
Raise_Pen,
(-1, -3),
(-1, 3),
Raise_Pen,
(0, -3),
(0, 3),
Raise_Pen,
(1, -3),
(1, 3),
Raise_Pen,
(2, -2),
(2, 2),
Raise_Pen,
(3, -1),
(3, 1)));
   Glyph_43 : aliased constant Glyph :=
     (Number_Of_Vectors => 27,
      Width => 8,
      Height => 8,
      Y_Offset => -4,
      X_Offset => -4,
      Vects => (Raise_Pen,
(-4, -4),
(-4, 4),
(4, 4),
(4, -4),
(-4, -4),
Raise_Pen,
(-3, -3),
(-3, 3),
Raise_Pen,
(-2, -3),
(-2, 3),
Raise_Pen,
(-1, -3),
(-1, 3),
Raise_Pen,
(0, -3),
(0, 3),
Raise_Pen,
(1, -3),
(1, 3),
Raise_Pen,
(2, -3),
(2, 3),
Raise_Pen,
(3, -3),
(3, 3)));
   Glyph_44 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 10,
      Height => 9,
      Y_Offset => -6,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, -6),
(-5, 3),
(5, 3),
(0, -6),
Raise_Pen,
(0, -3),
(-3, 2),
Raise_Pen,
(0, -3),
(3, 2),
Raise_Pen,
(0, 0),
(-1, 2),
Raise_Pen,
(0, 0),
(1, 2)));
   Glyph_45 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 9,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-6, 0),
(3, 5),
(3, -5),
(-6, 0),
Raise_Pen,
(-3, 0),
(2, 3),
Raise_Pen,
(-3, 0),
(2, -3),
Raise_Pen,
(0, 0),
(2, 1),
Raise_Pen,
(0, 0),
(2, -1)));
   Glyph_46 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 10,
      Height => 9,
      Y_Offset => -3,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, 6),
(5, -3),
(-5, -3),
(0, 6),
Raise_Pen,
(0, 3),
(3, -2),
Raise_Pen,
(0, 3),
(-3, -2),
Raise_Pen,
(0, 0),
(1, -2),
Raise_Pen,
(0, 0),
(-1, -2)));
   Glyph_47 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 9,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -3,
      Vects => (Raise_Pen,
(6, 0),
(-3, -5),
(-3, 5),
(6, 0),
Raise_Pen,
(3, 0),
(-2, -3),
Raise_Pen,
(3, 0),
(-2, 3),
Raise_Pen,
(0, 0),
(-2, -1),
Raise_Pen,
(0, 0),
(-2, 1)));
   Glyph_48 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Width => 28,
      Height => 16,
      Y_Offset => 0,
      X_Offset => -14,
      Vects => (Raise_Pen,
(-14, 0),
(14, 0),
Raise_Pen,
(-14, 0),
(0, 16),
Raise_Pen,
(14, 0),
(0, 16)));
   Glyph_49 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_50 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_51 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_52 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_53 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_54 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_55 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_56 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_57 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_58 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_59 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_60 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_61 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_62 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_63 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_64 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_65 : aliased constant Glyph :=
     (Number_Of_Vectors => 18,
      Width => 14,
      Height => 14,
      Y_Offset => -7,
      X_Offset => -7,
      Vects => (Raise_Pen,
(-1, -7),
(-4, -6),
(-6, -4),
(-7, -1),
(-7, 1),
(-6, 4),
(-4, 6),
(-1, 7),
(1, 7),
(4, 6),
(6, 4),
(7, 1),
(7, -1),
(6, -4),
(4, -6),
(1, -7),
(-1, -7)));
   Glyph_66 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 12,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-6, -6),
(-6, 6),
(6, 6),
(6, -6),
(-6, -6)));
   Glyph_67 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Width => 14,
      Height => 12,
      Y_Offset => -8,
      X_Offset => -7,
      Vects => (Raise_Pen,
(0, -8),
(-7, 4),
(7, 4),
(0, -8)));
   Glyph_68 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 12,
      Height => 20,
      Y_Offset => -10,
      X_Offset => -6,
      Vects => (Raise_Pen,
(0, -10),
(-6, 0),
(0, 10),
(6, 0),
(0, -10)));
   Glyph_69 : aliased constant Glyph :=
     (Number_Of_Vectors => 12,
      Width => 16,
      Height => 16,
      Y_Offset => -9,
      X_Offset => -8,
      Vects => (Raise_Pen,
(0, -9),
(-2, -3),
(-8, -3),
(-3, 1),
(-5, 7),
(0, 3),
(5, 7),
(3, 1),
(8, -3),
(2, -3),
(0, -9)));
   Glyph_70 : aliased constant Glyph :=
     (Number_Of_Vectors => 14,
      Width => 12,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-2, -6),
(-2, -2),
(-6, -2),
(-6, 2),
(-2, 2),
(-2, 6),
(2, 6),
(2, 2),
(6, 2),
(6, -2),
(2, -2),
(2, -6),
(-2, -6)));
   Glyph_71 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 14,
      Height => 14,
      Y_Offset => -7,
      X_Offset => -7,
      Vects => (Raise_Pen,
(0, -7),
(0, 7),
Raise_Pen,
(-7, 0),
(7, 0)));
   Glyph_72 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Width => 10,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -5,
      Vects => (Raise_Pen,
(-5, -5),
(5, 5),
Raise_Pen,
(5, -5),
(-5, 5)));
   Glyph_73 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Width => 10,
      Height => 12,
      Y_Offset => -6,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, -6),
(0, 6),
Raise_Pen,
(-5, -3),
(5, 3),
Raise_Pen,
(5, -3),
(-5, 3)));
   Glyph_74 : aliased constant Glyph :=
     (Number_Of_Vectors => 35,
      Width => 8,
      Height => 8,
      Y_Offset => -4,
      X_Offset => -4,
      Vects => (Raise_Pen,
(-1, -4),
(-3, -3),
(-4, -1),
(-4, 1),
(-3, 3),
(-1, 4),
(1, 4),
(3, 3),
(4, 1),
(4, -1),
(3, -3),
(1, -4),
(-1, -4),
Raise_Pen,
(-3, -1),
(-3, 1),
Raise_Pen,
(-2, -2),
(-2, 2),
Raise_Pen,
(-1, -3),
(-1, 3),
Raise_Pen,
(0, -3),
(0, 3),
Raise_Pen,
(1, -3),
(1, 3),
Raise_Pen,
(2, -2),
(2, 2),
Raise_Pen,
(3, -1),
(3, 1)));
   Glyph_75 : aliased constant Glyph :=
     (Number_Of_Vectors => 27,
      Width => 8,
      Height => 8,
      Y_Offset => -4,
      X_Offset => -4,
      Vects => (Raise_Pen,
(-4, -4),
(-4, 4),
(4, 4),
(4, -4),
(-4, -4),
Raise_Pen,
(-3, -3),
(-3, 3),
Raise_Pen,
(-2, -3),
(-2, 3),
Raise_Pen,
(-1, -3),
(-1, 3),
Raise_Pen,
(0, -3),
(0, 3),
Raise_Pen,
(1, -3),
(1, 3),
Raise_Pen,
(2, -3),
(2, 3),
Raise_Pen,
(3, -3),
(3, 3)));
   Glyph_76 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 10,
      Height => 9,
      Y_Offset => -6,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, -6),
(-5, 3),
(5, 3),
(0, -6),
Raise_Pen,
(0, -3),
(-3, 2),
Raise_Pen,
(0, -3),
(3, 2),
Raise_Pen,
(0, 0),
(-1, 2),
Raise_Pen,
(0, 0),
(1, 2)));
   Glyph_77 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 9,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -6,
      Vects => (Raise_Pen,
(-6, 0),
(3, 5),
(3, -5),
(-6, 0),
Raise_Pen,
(-3, 0),
(2, 3),
Raise_Pen,
(-3, 0),
(2, -3),
Raise_Pen,
(0, 0),
(2, 1),
Raise_Pen,
(0, 0),
(2, -1)));
   Glyph_78 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 10,
      Height => 9,
      Y_Offset => -3,
      X_Offset => -5,
      Vects => (Raise_Pen,
(0, 6),
(5, -3),
(-5, -3),
(0, 6),
Raise_Pen,
(0, 3),
(3, -2),
Raise_Pen,
(0, 3),
(-3, -2),
Raise_Pen,
(0, 0),
(1, -2),
Raise_Pen,
(0, 0),
(-1, -2)));
   Glyph_79 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Width => 9,
      Height => 10,
      Y_Offset => -5,
      X_Offset => -3,
      Vects => (Raise_Pen,
(6, 0),
(-3, -5),
(-3, 5),
(6, 0),
Raise_Pen,
(3, 0),
(-2, -3),
Raise_Pen,
(3, 0),
(-2, 3),
Raise_Pen,
(0, 0),
(-2, -1),
Raise_Pen,
(0, 0),
(-2, 1)));
   Glyph_80 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Width => 28,
      Height => 16,
      Y_Offset => 0,
      X_Offset => -14,
      Vects => (Raise_Pen,
(-14, 0),
(14, 0),
Raise_Pen,
(-14, 0),
(0, 16),
Raise_Pen,
(14, 0),
(0, 16)));
   Glyph_81 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_82 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_83 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_84 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_85 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_86 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_87 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_88 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_89 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_90 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_91 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_92 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_93 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_94 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_95 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));
   Glyph_96 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Width => 16,
      Height => 0,
      Y_Offset => 0,
      X_Offset => -8,
      Vects => (others => (Raise_Pen)));

   Font_D : aliased constant Hershey_Font :=
     (Number_Of_Glyphs => 97,
      Glyphs =>
        (
         Glyph_0'Access,
         Glyph_1'Access,
         Glyph_2'Access,
         Glyph_3'Access,
         Glyph_4'Access,
         Glyph_5'Access,
         Glyph_6'Access,
         Glyph_7'Access,
         Glyph_8'Access,
         Glyph_9'Access,
         Glyph_10'Access,
         Glyph_11'Access,
         Glyph_12'Access,
         Glyph_13'Access,
         Glyph_14'Access,
         Glyph_15'Access,
         Glyph_16'Access,
         Glyph_17'Access,
         Glyph_18'Access,
         Glyph_19'Access,
         Glyph_20'Access,
         Glyph_21'Access,
         Glyph_22'Access,
         Glyph_23'Access,
         Glyph_24'Access,
         Glyph_25'Access,
         Glyph_26'Access,
         Glyph_27'Access,
         Glyph_28'Access,
         Glyph_29'Access,
         Glyph_30'Access,
         Glyph_31'Access,
         Glyph_32'Access,
         Glyph_33'Access,
         Glyph_34'Access,
         Glyph_35'Access,
         Glyph_36'Access,
         Glyph_37'Access,
         Glyph_38'Access,
         Glyph_39'Access,
         Glyph_40'Access,
         Glyph_41'Access,
         Glyph_42'Access,
         Glyph_43'Access,
         Glyph_44'Access,
         Glyph_45'Access,
         Glyph_46'Access,
         Glyph_47'Access,
         Glyph_48'Access,
         Glyph_49'Access,
         Glyph_50'Access,
         Glyph_51'Access,
         Glyph_52'Access,
         Glyph_53'Access,
         Glyph_54'Access,
         Glyph_55'Access,
         Glyph_56'Access,
         Glyph_57'Access,
         Glyph_58'Access,
         Glyph_59'Access,
         Glyph_60'Access,
         Glyph_61'Access,
         Glyph_62'Access,
         Glyph_63'Access,
         Glyph_64'Access,
         Glyph_65'Access,
         Glyph_66'Access,
         Glyph_67'Access,
         Glyph_68'Access,
         Glyph_69'Access,
         Glyph_70'Access,
         Glyph_71'Access,
         Glyph_72'Access,
         Glyph_73'Access,
         Glyph_74'Access,
         Glyph_75'Access,
         Glyph_76'Access,
         Glyph_77'Access,
         Glyph_78'Access,
         Glyph_79'Access,
         Glyph_80'Access,
         Glyph_81'Access,
         Glyph_82'Access,
         Glyph_83'Access,
         Glyph_84'Access,
         Glyph_85'Access,
         Glyph_86'Access,
         Glyph_87'Access,
         Glyph_88'Access,
         Glyph_89'Access,
         Glyph_90'Access,
         Glyph_91'Access,
         Glyph_92'Access,
         Glyph_93'Access,
         Glyph_94'Access,
         Glyph_95'Access,
         Glyph_96'Access
        ), Y_Advance => 20);
   Font : constant Giza.Font.Ref_Const := Font_D'Access;
end Giza.Hershey_Fonts.Markers;
