package Hershey_Fonts.Symbolic is
   Font : constant Font_Access;
private
   Glyph_0 : aliased constant Glyph :=
     (Number_Of_Vectors => 0,
      Charcode          => 0,
      Left              => -8,
      Right             => 8,
      Top               => 0,
      Bottom            => 0,
      Vects             => (others => (Raise_Pen)));
   Glyph_1 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 1,
      Left              => -14,
      Right             => 14,
      Top               => 0,
      Bottom            => 0,
      Vects             => (Raise_Pen, (-14, 0), (14, 0)));
   Glyph_2 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 2,
      Left              => -14,
      Right             => 14,
      Top               => -14,
      Bottom            => 14,
      Vects             => (Raise_Pen, (-14, 14), (14, -14)));
   Glyph_3 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 3,
      Left              => 0,
      Right             => 0,
      Top               => -20,
      Bottom            => 20,
      Vects             => (Raise_Pen, (0, -20), (0, 20)));
   Glyph_4 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 4,
      Left              => -14,
      Right             => 14,
      Top               => -14,
      Bottom            => 14,
      Vects             => (Raise_Pen, (-14, -14), (14, 14)));
   Glyph_5 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 5,
      Left              => -14,
      Right             => 14,
      Top               => 0,
      Bottom            => 0,
      Vects             => (Raise_Pen, (-14, 0), (14, 0)));
   Glyph_6 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 6,
      Left              => -12,
      Right             => 12,
      Top               => -7,
      Bottom            => 7,
      Vects             => (Raise_Pen, (-12, 7), (12, -7)));
   Glyph_7 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 7,
      Left              => -7,
      Right             => 7,
      Top               => -12,
      Bottom            => 12,
      Vects             => (Raise_Pen, (-7, 12), (7, -12)));
   Glyph_8 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 8,
      Left              => 0,
      Right             => 0,
      Top               => -14,
      Bottom            => 14,
      Vects             => (Raise_Pen, (0, -14), (0, 14)));
   Glyph_9 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 9,
      Left              => -7,
      Right             => 7,
      Top               => -12,
      Bottom            => 12,
      Vects             => (Raise_Pen, (-7, -12), (7, 12)));
   Glyph_10 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 10,
      Left              => -12,
      Right             => 12,
      Top               => -7,
      Bottom            => 7,
      Vects             => (Raise_Pen, (-12, -7), (12, 7)));
   Glyph_11 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 11,
      Left              => -7,
      Right             => 7,
      Top               => 0,
      Bottom            => 0,
      Vects             => (Raise_Pen, (-7, 0), (7, 0)));
   Glyph_12 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 12,
      Left              => -5,
      Right             => 5,
      Top               => -5,
      Bottom            => 5,
      Vects             => (Raise_Pen, (-5, 5), (5, -5)));
   Glyph_13 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 13,
      Left              => 0,
      Right             => 0,
      Top               => -7,
      Bottom            => 7,
      Vects             => (Raise_Pen, (0, -7), (0, 7)));
   Glyph_14 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 14,
      Left              => -5,
      Right             => 5,
      Top               => -5,
      Bottom            => 5,
      Vects             => (Raise_Pen, (-5, -5), (5, 5)));
   Glyph_15 : aliased constant Glyph :=
     (Number_Of_Vectors => 8,
      Charcode          => 15,
      Left              => -11,
      Right             => 0,
      Top               => -11,
      Bottom            => 0,
      Vects             =>
        (Raise_Pen,
         (0, -11),
         (-2, -11),
         (-5, -10),
         (-8, -8),
         (-10, -5),
         (-11, -2),
         (-11, 0)));
   Glyph_16 : aliased constant Glyph :=
     (Number_Of_Vectors => 8,
      Charcode          => 16,
      Left              => -11,
      Right             => 0,
      Top               => 0,
      Bottom            => 11,
      Vects             =>
        (Raise_Pen,
         (-11, 0),
         (-11, 2),
         (-10, 5),
         (-8, 8),
         (-5, 10),
         (-2, 11),
         (0, 11)));
   Glyph_17 : aliased constant Glyph :=
     (Number_Of_Vectors => 8,
      Charcode          => 17,
      Left              => 0,
      Right             => 11,
      Top               => 0,
      Bottom            => 11,
      Vects             =>
        (Raise_Pen,
         (0, 11),
         (2, 11),
         (5, 10),
         (8, 8),
         (10, 5),
         (11, 2),
         (11, 0)));
   Glyph_18 : aliased constant Glyph :=
     (Number_Of_Vectors => 8,
      Charcode          => 18,
      Left              => 0,
      Right             => 11,
      Top               => -11,
      Bottom            => 0,
      Vects             =>
        (Raise_Pen,
         (11, 0),
         (11, -2),
         (10, -5),
         (8, -8),
         (5, -10),
         (2, -11),
         (0, -11)));
   Glyph_19 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 19,
      Left              => -14,
      Right             => 14,
      Top               => -3,
      Bottom            => 2,
      Vects             =>
        (Raise_Pen,
         (-14, -3),
         (-11, -1),
         (-7, 1),
         (-2, 2),
         (2, 2),
         (7, 1),
         (11, -1),
         (14, -3)));
   Glyph_20 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 20,
      Left              => -2,
      Right             => 3,
      Top               => -14,
      Bottom            => 14,
      Vects             =>
        (Raise_Pen,
         (3, -14),
         (1, -11),
         (-1, -7),
         (-2, -2),
         (-2, 2),
         (-1, 7),
         (1, 11),
         (3, 14)));
   Glyph_21 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 21,
      Left              => -3,
      Right             => 2,
      Top               => -14,
      Bottom            => 14,
      Vects             =>
        (Raise_Pen,
         (-3, -14),
         (-1, -11),
         (1, -7),
         (2, -2),
         (2, 2),
         (1, 7),
         (-1, 11),
         (-3, 14)));
   Glyph_22 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 22,
      Left              => -14,
      Right             => 14,
      Top               => -2,
      Bottom            => 3,
      Vects             =>
        (Raise_Pen,
         (-14, 3),
         (-11, 1),
         (-7, -1),
         (-2, -2),
         (2, -2),
         (7, -1),
         (11, 1),
         (14, 3)));
   Glyph_23 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 23,
      Left              => -7,
      Right             => 7,
      Top               => -8,
      Bottom            => 8,
      Vects             => (Raise_Pen, (0, -8), (7, -4), (-7, 4), (0, 8)));
   Glyph_24 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 24,
      Left              => -8,
      Right             => 8,
      Top               => -7,
      Bottom            => 7,
      Vects             => (Raise_Pen, (-8, 0), (-4, -7), (4, 7), (8, 0)));
   Glyph_25 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 25,
      Left              => -7,
      Right             => 7,
      Top               => -4,
      Bottom            => 4,
      Vects             => (Raise_Pen, (-7, 4), (-7, -4), (7, 4), (7, -4)));
   Glyph_26 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 26,
      Left              => -8,
      Right             => 8,
      Top               => -6,
      Bottom            => 6,
      Vects             => (Raise_Pen, (-6, 6), (-8, -2), (8, 2), (6, -6)));
   Glyph_27 : aliased constant Glyph :=
     (Number_Of_Vectors => 23,
      Charcode          => 27,
      Left              => -8,
      Right             => 8,
      Top               => -9,
      Bottom            => 11,
      Vects             =>
        (Raise_Pen,
         (-8, 11),
         (-6, 11),
         (-3, 10),
         (-1, 9),
         (2, 6),
         (3, 4),
         (4, 1),
         (4, -3),
         (3, -6),
         (2, -8),
         (1, -9),
         (-1, -9),
         (-2, -8),
         (-3, -6),
         (-4, -3),
         (-4, 1),
         (-3, 4),
         (-2, 6),
         (1, 9),
         (3, 10),
         (6, 11),
         (8, 11)));
   Glyph_28 : aliased constant Glyph :=
     (Number_Of_Vectors => 23,
      Charcode          => 28,
      Left              => -9,
      Right             => 11,
      Top               => -8,
      Bottom            => 8,
      Vects             =>
        (Raise_Pen,
         (11, 8),
         (11, 6),
         (10, 3),
         (9, 1),
         (6, -2),
         (4, -3),
         (1, -4),
         (-3, -4),
         (-6, -3),
         (-8, -2),
         (-9, -1),
         (-9, 1),
         (-8, 2),
         (-6, 3),
         (-3, 4),
         (1, 4),
         (4, 3),
         (6, 2),
         (9, -1),
         (10, -3),
         (11, -6),
         (11, -8)));
   Glyph_29 : aliased constant Glyph :=
     (Number_Of_Vectors => 23,
      Charcode          => 29,
      Left              => -8,
      Right             => 8,
      Top               => -11,
      Bottom            => 9,
      Vects             =>
        (Raise_Pen,
         (8, -11),
         (6, -11),
         (3, -10),
         (1, -9),
         (-2, -6),
         (-3, -4),
         (-4, -1),
         (-4, 3),
         (-3, 6),
         (-2, 8),
         (-1, 9),
         (1, 9),
         (2, 8),
         (3, 6),
         (4, 3),
         (4, -1),
         (3, -4),
         (2, -6),
         (-1, -9),
         (-3, -10),
         (-6, -11),
         (-8, -11)));
   Glyph_30 : aliased constant Glyph :=
     (Number_Of_Vectors => 23,
      Charcode          => 30,
      Left              => -11,
      Right             => 9,
      Top               => -8,
      Bottom            => 8,
      Vects             =>
        (Raise_Pen,
         (-11, -8),
         (-11, -6),
         (-10, -3),
         (-9, -1),
         (-6, 2),
         (-4, 3),
         (-1, 4),
         (3, 4),
         (6, 3),
         (8, 2),
         (9, 1),
         (9, -1),
         (8, -2),
         (6, -3),
         (3, -4),
         (-1, -4),
         (-4, -3),
         (-6, -2),
         (-9, 1),
         (-10, 3),
         (-11, 6),
         (-11, 8)));
   Glyph_31 : aliased constant Glyph :=
     (Number_Of_Vectors => 21,
      Charcode          => 31,
      Left              => -13,
      Right             => 9,
      Top               => -6,
      Bottom            => 12,
      Vects             =>
        (Raise_Pen,
         (-13, -2),
         (-12, 0),
         (-10, 2),
         (-8, 3),
         (-5, 4),
         (-1, 4),
         (3, 3),
         (6, 1),
         (8, -2),
         (9, -4),
         (8, -6),
         (5, -6),
         (1, -5),
         (-1, -4),
         (-4, -2),
         (-6, 1),
         (-7, 4),
         (-7, 7),
         (-6, 10),
         (-5, 12)));
   Glyph_32 : aliased constant Glyph :=
     (Number_Of_Vectors => 19,
      Charcode          => 32,
      Left              => -13,
      Right             => 7,
      Top               => -7,
      Bottom            => 13,
      Vects             =>
        (Raise_Pen,
         (-13, 2),
         (-10, 4),
         (-7, 5),
         (-2, 5),
         (1, 4),
         (4, 2),
         (6, -1),
         (7, -4),
         (7, -6),
         (6, -7),
         (4, -7),
         (1, -6),
         (-2, -4),
         (-4, -1),
         (-5, 2),
         (-5, 7),
         (-4, 10),
         (-2, 13)));
   Glyph_33 : aliased constant Glyph :=
     (Number_Of_Vectors => 26,
      Charcode          => 33,
      Left              => -3,
      Right             => 3,
      Top               => -3,
      Bottom            => 3,
      Vects             =>
        (Raise_Pen,
         (-1, -3),
         (-3, -1),
         (-3, 1),
         (-1, 3),
         (1, 3),
         (3, 1),
         (3, -1),
         (1, -3),
         (-1, -3),
         Raise_Pen,
         (-1, -2),
         (-2, -1),
         (-2, 1),
         (-1, 2),
         (1, 2),
         (2, 1),
         (2, -1),
         (1, -2),
         (-1, -2),
         Raise_Pen,
         (0, -1),
         (-1, 0),
         (0, 1),
         (1, 0),
         (0, -1)));
   Glyph_34 : aliased constant Glyph :=
     (Number_Of_Vectors => 11,
      Charcode          => 34,
      Left              => 0,
      Right             => 5,
      Top               => -5,
      Bottom            => 5,
      Vects             =>
        (Raise_Pen,
         (0, -5),
         (1, -5),
         (3, -4),
         (4, -3),
         (5, -1),
         (5, 1),
         (4, 3),
         (3, 4),
         (1, 5),
         (0, 5)));
   Glyph_35 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 35,
      Left              => -14,
      Right             => 14,
      Top               => 0,
      Bottom            => 0,
      Vects             =>
        (Raise_Pen,
         (-14, 0),
         (-8, 0),
         Raise_Pen,
         (-3, 0),
         (3, 0),
         Raise_Pen,
         (8, 0),
         (14, 0)));
   Glyph_36 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 36,
      Left              => -14,
      Right             => 14,
      Top               => -3,
      Bottom            => 3,
      Vects => (Raise_Pen, (-14, 3), (-14, -3), (14, -3), (14, 3)));
   Glyph_37 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Charcode          => 37,
      Left              => -8,
      Right             => 8,
      Top               => -14,
      Bottom            => 0,
      Vects => (Raise_Pen, (0, -14), (-8, 0), Raise_Pen, (0, -14), (8, 0)));
   Glyph_38 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 38,
      Left              => -14,
      Right             => 14,
      Top               => 0,
      Bottom            => 14,
      Vects             =>
        (Raise_Pen,
         (-14, 0),
         (14, 0),
         Raise_Pen,
         (-8, 7),
         (8, 7),
         Raise_Pen,
         (-2, 14),
         (2, 14)));
   Glyph_39 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 39,
      Left              => -14,
      Right             => 14,
      Top               => 0,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (-14, 0),
         (14, 0),
         Raise_Pen,
         (-14, 0),
         (0, 16),
         Raise_Pen,
         (14, 0),
         (0, 16)));
   Glyph_40 : aliased constant Glyph :=
     (Number_Of_Vectors => 18,
      Charcode          => 40,
      Left              => -7,
      Right             => 7,
      Top               => -7,
      Bottom            => 7,
      Vects             =>
        (Raise_Pen,
         (-1, -7),
         (-4, -6),
         (-6, -4),
         (-7, -1),
         (-7, 1),
         (-6, 4),
         (-4, 6),
         (-1, 7),
         (1, 7),
         (4, 6),
         (6, 4),
         (7, 1),
         (7, -1),
         (6, -4),
         (4, -6),
         (1, -7),
         (-1, -7)));
   Glyph_41 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Charcode          => 41,
      Left              => -6,
      Right             => 6,
      Top               => -6,
      Bottom            => 6,
      Vects => (Raise_Pen, (-6, -6), (-6, 6), (6, 6), (6, -6), (-6, -6)));
   Glyph_42 : aliased constant Glyph :=
     (Number_Of_Vectors => 5,
      Charcode          => 42,
      Left              => -7,
      Right             => 7,
      Top               => -8,
      Bottom            => 4,
      Vects             => (Raise_Pen, (0, -8), (-7, 4), (7, 4), (0, -8)));
   Glyph_43 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Charcode          => 43,
      Left              => -6,
      Right             => 6,
      Top               => -10,
      Bottom            => 10,
      Vects => (Raise_Pen, (0, -10), (-6, 0), (0, 10), (6, 0), (0, -10)));
   Glyph_44 : aliased constant Glyph :=
     (Number_Of_Vectors => 12,
      Charcode          => 44,
      Left              => -8,
      Right             => 8,
      Top               => -9,
      Bottom            => 7,
      Vects             =>
        (Raise_Pen,
         (0, -9),
         (-2, -3),
         (-8, -3),
         (-3, 1),
         (-5, 7),
         (0, 3),
         (5, 7),
         (3, 1),
         (8, -3),
         (2, -3),
         (0, -9)));
   Glyph_45 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Charcode          => 45,
      Left              => -7,
      Right             => 7,
      Top               => -7,
      Bottom            => 7,
      Vects => (Raise_Pen, (0, -7), (0, 7), Raise_Pen, (-7, 0), (7, 0)));
   Glyph_46 : aliased constant Glyph :=
     (Number_Of_Vectors => 6,
      Charcode          => 46,
      Left              => -5,
      Right             => 5,
      Top               => -5,
      Bottom            => 5,
      Vects => (Raise_Pen, (-5, -5), (5, 5), Raise_Pen, (5, -5), (-5, 5)));
   Glyph_47 : aliased constant Glyph :=
     (Number_Of_Vectors => 9,
      Charcode          => 47,
      Left              => -5,
      Right             => 5,
      Top               => -6,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (0, -6),
         (0, 6),
         Raise_Pen,
         (-5, -3),
         (5, 3),
         Raise_Pen,
         (5, -3),
         (-5, 3)));
   Glyph_48 : aliased constant Glyph :=
     (Number_Of_Vectors => 35,
      Charcode          => 48,
      Left              => -4,
      Right             => 4,
      Top               => -4,
      Bottom            => 4,
      Vects             =>
        (Raise_Pen,
         (-1, -4),
         (-3, -3),
         (-4, -1),
         (-4, 1),
         (-3, 3),
         (-1, 4),
         (1, 4),
         (3, 3),
         (4, 1),
         (4, -1),
         (3, -3),
         (1, -4),
         (-1, -4),
         Raise_Pen,
         (-3, -1),
         (-3, 1),
         Raise_Pen,
         (-2, -2),
         (-2, 2),
         Raise_Pen,
         (-1, -3),
         (-1, 3),
         Raise_Pen,
         (0, -3),
         (0, 3),
         Raise_Pen,
         (1, -3),
         (1, 3),
         Raise_Pen,
         (2, -2),
         (2, 2),
         Raise_Pen,
         (3, -1),
         (3, 1)));
   Glyph_49 : aliased constant Glyph :=
     (Number_Of_Vectors => 27,
      Charcode          => 49,
      Left              => -4,
      Right             => 4,
      Top               => -4,
      Bottom            => 4,
      Vects             =>
        (Raise_Pen,
         (-4, -4),
         (-4, 4),
         (4, 4),
         (4, -4),
         (-4, -4),
         Raise_Pen,
         (-3, -3),
         (-3, 3),
         Raise_Pen,
         (-2, -3),
         (-2, 3),
         Raise_Pen,
         (-1, -3),
         (-1, 3),
         Raise_Pen,
         (0, -3),
         (0, 3),
         Raise_Pen,
         (1, -3),
         (1, 3),
         Raise_Pen,
         (2, -3),
         (2, 3),
         Raise_Pen,
         (3, -3),
         (3, 3)));
   Glyph_50 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Charcode          => 50,
      Left              => -5,
      Right             => 5,
      Top               => -6,
      Bottom            => 3,
      Vects             =>
        (Raise_Pen,
         (0, -6),
         (-5, 3),
         (5, 3),
         (0, -6),
         Raise_Pen,
         (0, -3),
         (-3, 2),
         Raise_Pen,
         (0, -3),
         (3, 2),
         Raise_Pen,
         (0, 0),
         (-1, 2),
         Raise_Pen,
         (0, 0),
         (1, 2)));
   Glyph_51 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Charcode          => 51,
      Left              => -6,
      Right             => 3,
      Top               => -5,
      Bottom            => 5,
      Vects             =>
        (Raise_Pen,
         (-6, 0),
         (3, 5),
         (3, -5),
         (-6, 0),
         Raise_Pen,
         (-3, 0),
         (2, 3),
         Raise_Pen,
         (-3, 0),
         (2, -3),
         Raise_Pen,
         (0, 0),
         (2, 1),
         Raise_Pen,
         (0, 0),
         (2, -1)));
   Glyph_52 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Charcode          => 52,
      Left              => -5,
      Right             => 5,
      Top               => -3,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (0, 6),
         (5, -3),
         (-5, -3),
         (0, 6),
         Raise_Pen,
         (0, 3),
         (3, -2),
         Raise_Pen,
         (0, 3),
         (-3, -2),
         Raise_Pen,
         (0, 0),
         (1, -2),
         Raise_Pen,
         (0, 0),
         (-1, -2)));
   Glyph_53 : aliased constant Glyph :=
     (Number_Of_Vectors => 17,
      Charcode          => 53,
      Left              => -3,
      Right             => 6,
      Top               => -5,
      Bottom            => 5,
      Vects             =>
        (Raise_Pen,
         (6, 0),
         (-3, -5),
         (-3, 5),
         (6, 0),
         Raise_Pen,
         (3, 0),
         (-2, -3),
         Raise_Pen,
         (3, 0),
         (-2, 3),
         Raise_Pen,
         (0, 0),
         (-2, -1),
         Raise_Pen,
         (0, 0),
         (-2, 1)));
   Glyph_54 : aliased constant Glyph :=
     (Number_Of_Vectors => 11,
      Charcode          => 54,
      Left              => 0,
      Right             => 7,
      Top               => -7,
      Bottom            => 7,
      Vects             =>
        (Raise_Pen,
         (0, -7),
         (0, 7),
         Raise_Pen,
         (0, -7),
         (7, -4),
         (0, -1),
         Raise_Pen,
         (1, -5),
         (4, -4),
         (1, -3)));
   Glyph_55 : aliased constant Glyph :=
     (Number_Of_Vectors => 21,
      Charcode          => 55,
      Left              => -9,
      Right             => 9,
      Top               => -11,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, -11),
         (0, 4),
         Raise_Pen,
         (-5, -8),
         (5, -2),
         Raise_Pen,
         (5, -8),
         (-5, -2),
         Raise_Pen,
         (-9, 4),
         (-6, 10),
         Raise_Pen,
         (9, 4),
         (6, 10),
         Raise_Pen,
         (-9, 4),
         (9, 4),
         Raise_Pen,
         (-6, 10),
         (6, 10)));
   Glyph_56 : aliased constant Glyph :=
     (Number_Of_Vectors => 13,
      Charcode          => 56,
      Left              => -5,
      Right             => 5,
      Top               => -6,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (0, -6),
         (0, 6),
         Raise_Pen,
         (-3, -3),
         (3, -3),
         Raise_Pen,
         (-5, 3),
         (-3, 5),
         (-1, 6),
         (1, 6),
         (3, 5),
         (5, 3)));
   Glyph_57 : aliased constant Glyph :=
     (Number_Of_Vectors => 11,
      Charcode          => 57,
      Left              => -6,
      Right             => 6,
      Top               => -6,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (0, -6),
         (0, 6),
         Raise_Pen,
         (-6, -1),
         (-5, -3),
         (5, -3),
         (6, -1),
         Raise_Pen,
         (-2, 5),
         (2, 5)));
   Glyph_58 : aliased constant Glyph :=
     (Number_Of_Vectors => 14,
      Charcode          => 58,
      Left              => -7,
      Right             => 7,
      Top               => -6,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (-5, -4),
         (5, 6),
         Raise_Pen,
         (5, -4),
         (-5, 6),
         Raise_Pen,
         (-3, -6),
         (-6, -3),
         (-7, -1),
         Raise_Pen,
         (3, -6),
         (6, -3),
         (7, -1)));
   Glyph_59 : aliased constant Glyph :=
     (Number_Of_Vectors => 18,
      Charcode          => 59,
      Left              => -9,
      Right             => 9,
      Top               => -9,
      Bottom            => 9,
      Vects             =>
        (Raise_Pen,
         (-4, -9),
         (-9, 9),
         Raise_Pen,
         (4, -9),
         (9, 9),
         Raise_Pen,
         (-5, -5),
         (9, 9),
         Raise_Pen,
         (5, -5),
         (-9, 9),
         Raise_Pen,
         (-4, -9),
         (4, -9),
         Raise_Pen,
         (-5, -5),
         (5, -5)));
   Glyph_60 : aliased constant Glyph :=
     (Number_Of_Vectors => 3,
      Charcode          => 60,
      Left              => -7,
      Right             => 7,
      Top               => -12,
      Bottom            => 12,
      Vects             => (Raise_Pen, (-7, -12), (7, 12)));
   Glyph_61 : aliased constant Glyph :=
     (Number_Of_Vectors => 11,
      Charcode          => 61,
      Left              => -11,
      Right             => 9,
      Top               => -8,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (-5, -8),
         (1, 4),
         Raise_Pen,
         (-7, -2),
         (1, -6),
         Raise_Pen,
         (-11, 10),
         (9, 10),
         (9, 0),
         (-11, 10)));
   Glyph_62 : aliased constant Glyph :=
     (Number_Of_Vectors => 14,
      Charcode          => 62,
      Left              => -6,
      Right             => 6,
      Top               => -6,
      Bottom            => 6,
      Vects             =>
        (Raise_Pen,
         (-2, -6),
         (-2, -2),
         (-6, -2),
         (-6, 2),
         (-2, 2),
         (-2, 6),
         (2, 6),
         (2, 2),
         (6, 2),
         (6, -2),
         (2, -2),
         (2, -6),
         (-2, -6)));
   Glyph_63 : aliased constant Glyph :=
     (Number_Of_Vectors => 32,
      Charcode          => 63,
      Left              => -7,
      Right             => 7,
      Top               => -7,
      Bottom            => 7,
      Vects             =>
        (Raise_Pen,
         (7, -2),
         (6, -4),
         (4, -6),
         (1, -7),
         (-1, -7),
         (-4, -6),
         (-6, -4),
         (-7, -1),
         (-7, 1),
         (-6, 4),
         (-4, 6),
         (-1, 7),
         (1, 7),
         (4, 6),
         (6, 4),
         (7, 2),
         Raise_Pen,
         (7, -2),
         (5, -4),
         (3, -5),
         (1, -5),
         (-1, -4),
         (-2, -3),
         (-3, -1),
         (-3, 1),
         (-2, 3),
         (-1, 4),
         (1, 5),
         (3, 5),
         (5, 4),
         (7, 2)));
   Glyph_64 : aliased constant Glyph :=
     (Number_Of_Vectors => 10,
      Charcode          => 64,
      Left              => -7,
      Right             => 7,
      Top               => -8,
      Bottom            => 8,
      Vects             =>
        (Raise_Pen,
         (0, -8),
         (-7, 4),
         (7, 4),
         (0, -8),
         Raise_Pen,
         (0, 8),
         (7, -4),
         (-7, -4),
         (0, 8)));
   Glyph_65 : aliased constant Glyph :=
     (Number_Of_Vectors => 34,
      Charcode          => 65,
      Left              => -11,
      Right             => 11,
      Top               => -12,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (-2, -9),
         (-2, -11),
         (-1, -12),
         (1, -12),
         (2, -11),
         (2, -9),
         Raise_Pen,
         (-11, 8),
         (-10, 6),
         (-8, 4),
         (-7, 2),
         (-6, -2),
         (-6, -7),
         (-5, -8),
         (-3, -9),
         (3, -9),
         (5, -8),
         (6, -7),
         (6, -2),
         (7, 2),
         (8, 4),
         (10, 6),
         (11, 8),
         Raise_Pen,
         (-11, 8),
         (11, 8),
         Raise_Pen,
         (-1, 8),
         (-2, 9),
         (-1, 10),
         (1, 10),
         (2, 9),
         (1, 8)));
   Glyph_66 : aliased constant Glyph :=
     (Number_Of_Vectors => 64,
      Charcode          => 66,
      Left              => -8,
      Right             => 8,
      Top               => -11,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, -5),
         (0, 1),
         Raise_Pen,
         (0, 1),
         (-1, 10),
         Raise_Pen,
         (0, 1),
         (1, 10),
         Raise_Pen,
         (-1, 10),
         (1, 10),
         Raise_Pen,
         (0, -5),
         (-1, -8),
         (-2, -10),
         (-4, -11),
         Raise_Pen,
         (-1, -8),
         (-4, -11),
         Raise_Pen,
         (0, -5),
         (1, -8),
         (2, -10),
         (4, -11),
         Raise_Pen,
         (1, -8),
         (4, -11),
         Raise_Pen,
         (0, -5),
         (-4, -7),
         (-6, -7),
         (-8, -5),
         Raise_Pen,
         (-2, -6),
         (-6, -6),
         (-8, -5),
         Raise_Pen,
         (0, -5),
         (4, -7),
         (6, -7),
         (8, -5),
         Raise_Pen,
         (2, -6),
         (6, -6),
         (8, -5),
         Raise_Pen,
         (0, -5),
         (-2, -4),
         (-3, -3),
         (-3, 0),
         Raise_Pen,
         (0, -5),
         (-2, -3),
         (-3, 0),
         Raise_Pen,
         (0, -5),
         (2, -4),
         (3, -3),
         (3, 0),
         Raise_Pen,
         (0, -5),
         (2, -3),
         (3, 0)));
   Glyph_67 : aliased constant Glyph :=
     (Number_Of_Vectors => 94,
      Charcode          => 67,
      Left              => -8,
      Right             => 8,
      Top               => -11,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, -9),
         (0, -7),
         Raise_Pen,
         (0, -4),
         (0, -2),
         Raise_Pen,
         (0, 1),
         (0, 3),
         Raise_Pen,
         (0, 7),
         (-1, 10),
         Raise_Pen,
         (0, 7),
         (1, 10),
         Raise_Pen,
         (-1, 10),
         (1, 10),
         Raise_Pen,
         (0, -11),
         (-1, -9),
         (-2, -8),
         Raise_Pen,
         (0, -11),
         (1, -9),
         (2, -8),
         Raise_Pen,
         (-2, -8),
         (0, -9),
         (2, -8),
         Raise_Pen,
         (0, -7),
         (-2, -4),
         (-4, -3),
         (-5, -4),
         Raise_Pen,
         (0, -7),
         (2, -4),
         (4, -3),
         (5, -4),
         Raise_Pen,
         (-4, -3),
         (-2, -3),
         (0, -4),
         (2, -3),
         (4, -3),
         Raise_Pen,
         (0, -2),
         (-2, 1),
         (-4, 2),
         (-6, 2),
         (-7, 0),
         (-7, 1),
         (-6, 2),
         Raise_Pen,
         (0, -2),
         (2, 1),
         (4, 2),
         (6, 2),
         (7, 0),
         (7, 1),
         (6, 2),
         Raise_Pen,
         (-4, 2),
         (-2, 2),
         (0, 1),
         (2, 2),
         (4, 2),
         Raise_Pen,
         (0, 3),
         (-2, 6),
         (-3, 7),
         (-5, 8),
         (-6, 8),
         (-7, 7),
         (-8, 5),
         (-8, 7),
         (-6, 8),
         Raise_Pen,
         (0, 3),
         (2, 6),
         (3, 7),
         (5, 8),
         (6, 8),
         (7, 7),
         (8, 5),
         (8, 7),
         (6, 8),
         Raise_Pen,
         (-5, 8),
         (-3, 8),
         (0, 7),
         (3, 8),
         (5, 8)));
   Glyph_68 : aliased constant Glyph :=
     (Number_Of_Vectors => 40,
      Charcode          => 68,
      Left              => -8,
      Right             => 8,
      Top               => -11,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, 7),
         (-1, 10),
         Raise_Pen,
         (0, 7),
         (1, 10),
         Raise_Pen,
         (-1, 10),
         (1, 10),
         Raise_Pen,
         (0, 7),
         (3, 8),
         (6, 8),
         (8, 6),
         (8, 3),
         (7, 2),
         (5, 2),
         (7, 0),
         (8, -3),
         (7, -5),
         (5, -6),
         (3, -5),
         (4, -8),
         (3, -10),
         (1, -11),
         (-1, -11),
         (-3, -10),
         (-4, -8),
         (-3, -5),
         (-5, -6),
         (-7, -5),
         (-8, -3),
         (-7, 0),
         (-5, 2),
         (-7, 2),
         (-8, 3),
         (-8, 6),
         (-6, 8),
         (-3, 8),
         (0, 7)));
   Glyph_69 : aliased constant Glyph :=
     (Number_Of_Vectors => 32,
      Charcode          => 69,
      Left              => -8,
      Right             => 8,
      Top               => -11,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, 7),
         (-1, 10),
         Raise_Pen,
         (0, 7),
         (1, 10),
         Raise_Pen,
         (-1, 10),
         (1, 10),
         Raise_Pen,
         (0, 7),
         (4, 6),
         (4, 4),
         (6, 3),
         (6, 0),
         (8, -1),
         (8, -6),
         (7, -9),
         (6, -10),
         (4, -10),
         (2, -11),
         (-2, -11),
         (-4, -10),
         (-6, -10),
         (-7, -9),
         (-8, -6),
         (-8, -1),
         (-6, 0),
         (-6, 3),
         (-4, 4),
         (-4, 6),
         (0, 7)));
   Glyph_70 : aliased constant Glyph :=
     (Number_Of_Vectors => 15,
      Charcode          => 70,
      Left              => -9,
      Right             => 9,
      Top               => -11,
      Bottom            => 0,
      Vects             =>
        (Raise_Pen,
         (-9, -2),
         (-7, 0),
         Raise_Pen,
         (-6, -7),
         (-4, -2),
         Raise_Pen,
         (0, -11),
         (0, -3),
         Raise_Pen,
         (6, -7),
         (4, -2),
         Raise_Pen,
         (9, -2),
         (7, 0)));
   Glyph_71 : aliased constant Glyph :=
     (Number_Of_Vectors => 28,
      Charcode          => 71,
      Left              => -11,
      Right             => 11,
      Top               => -9,
      Bottom            => 9,
      Vects             =>
        (Raise_Pen,
         (-9, -9),
         (-8, -7),
         (-7, -3),
         (-7, 3),
         (-8, 7),
         (-9, 9),
         Raise_Pen,
         (9, -9),
         (8, -7),
         (7, -3),
         (7, 3),
         (8, 7),
         (9, 9),
         Raise_Pen,
         (-9, -9),
         (-7, -8),
         (-3, -7),
         (3, -7),
         (7, -8),
         (9, -9),
         Raise_Pen,
         (-9, 9),
         (-7, 8),
         (-3, 7),
         (3, 7),
         (7, 8),
         (9, 9)));
   Glyph_72 : aliased constant Glyph :=
     (Number_Of_Vectors => 55,
      Charcode          => 72,
      Left              => -12,
      Right             => 12,
      Top               => -10,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, 0),
         (0, 9),
         (-1, 10),
         Raise_Pen,
         (0, 4),
         (-1, 10),
         Raise_Pen,
         (0, -9),
         (-1, -10),
         (-3, -10),
         (-4, -9),
         (-4, -7),
         (-3, -4),
         (0, 0),
         Raise_Pen,
         (0, -9),
         (1, -10),
         (3, -10),
         (4, -9),
         (4, -7),
         (3, -4),
         (0, 0),
         Raise_Pen,
         (0, 0),
         (-4, -3),
         (-6, -4),
         (-8, -4),
         (-9, -3),
         (-9, -1),
         (-8, 0),
         Raise_Pen,
         (0, 0),
         (4, -3),
         (6, -4),
         (8, -4),
         (9, -3),
         (9, -1),
         (8, 0),
         Raise_Pen,
         (0, 0),
         (-4, 3),
         (-6, 4),
         (-8, 4),
         (-9, 3),
         (-9, 1),
         (-8, 0),
         Raise_Pen,
         (0, 0),
         (4, 3),
         (6, 4),
         (8, 4),
         (9, 3),
         (9, 1),
         (8, 0)));
   Glyph_73 : aliased constant Glyph :=
     (Number_Of_Vectors => 46,
      Charcode          => 73,
      Left              => -8,
      Right             => 8,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (3, -9),
         (2, -8),
         (3, -7),
         (4, -8),
         (4, -9),
         (3, -11),
         (1, -12),
         (-1, -12),
         (-3, -11),
         (-4, -9),
         (-4, -7),
         (-3, -5),
         (-1, -3),
         (4, 0),
         Raise_Pen,
         (-3, -5),
         (2, -2),
         (4, 0),
         (5, 2),
         (5, 4),
         (4, 6),
         (2, 8),
         Raise_Pen,
         (-2, -4),
         (-4, -2),
         (-5, 0),
         (-5, 2),
         (-4, 4),
         (-2, 6),
         (3, 9),
         Raise_Pen,
         (-4, 4),
         (1, 7),
         (3, 9),
         (4, 11),
         (4, 13),
         (3, 15),
         (1, 16),
         (-1, 16),
         (-3, 15),
         (-4, 13),
         (-4, 12),
         (-3, 11),
         (-2, 12),
         (-3, 13)));
   Glyph_74 : aliased constant Glyph :=
     (Number_Of_Vectors => 30,
      Charcode          => 74,
      Left              => -8,
      Right             => 8,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (0, -12),
         (-1, -10),
         (0, -8),
         (1, -10),
         (0, -12),
         Raise_Pen,
         (0, -12),
         (0, 16),
         Raise_Pen,
         (0, -1),
         (-1, 2),
         (0, 16),
         (1, 2),
         (0, -1),
         Raise_Pen,
         (-6, -5),
         (-4, -4),
         (-2, -5),
         (-4, -6),
         (-6, -5),
         Raise_Pen,
         (-6, -5),
         (6, -5),
         Raise_Pen,
         (2, -5),
         (4, -4),
         (6, -5),
         (4, -6),
         (2, -5)));
   Glyph_75 : aliased constant Glyph :=
     (Number_Of_Vectors => 56,
      Charcode          => 75,
      Left              => -8,
      Right             => 8,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (0, -12),
         (-1, -10),
         (0, -8),
         (1, -10),
         (0, -12),
         Raise_Pen,
         (0, -12),
         (0, 2),
         Raise_Pen,
         (0, -2),
         (-1, 0),
         (1, 4),
         (0, 6),
         (-1, 4),
         (1, 0),
         (0, -2),
         Raise_Pen,
         (0, 2),
         (0, 16),
         Raise_Pen,
         (0, 12),
         (-1, 14),
         (0, 16),
         (1, 14),
         (0, 12),
         Raise_Pen,
         (-6, -5),
         (-4, -4),
         (-2, -5),
         (-4, -6),
         (-6, -5),
         Raise_Pen,
         (-6, -5),
         (6, -5),
         Raise_Pen,
         (2, -5),
         (4, -4),
         (6, -5),
         (4, -6),
         (2, -5),
         Raise_Pen,
         (-6, 9),
         (-4, 10),
         (-2, 9),
         (-4, 8),
         (-6, 9),
         Raise_Pen,
         (-6, 9),
         (6, 9),
         Raise_Pen,
         (2, 9),
         (4, 10),
         (6, 9),
         (4, 8),
         (2, 9)));
   Glyph_76 : aliased constant Glyph :=
     (Number_Of_Vectors => 18,
      Charcode          => 76,
      Left              => -13,
      Right             => 13,
      Top               => -9,
      Bottom            => 9,
      Vects             =>
        (Raise_Pen,
         (0, -9),
         (-1, -8),
         (0, -7),
         (1, -8),
         (0, -9),
         Raise_Pen,
         (-9, 7),
         (-10, 8),
         (-9, 9),
         (-8, 8),
         (-9, 7),
         Raise_Pen,
         (9, 7),
         (8, 8),
         (9, 9),
         (10, 8),
         (9, 7)));
   Glyph_77 : aliased constant Glyph :=
     (Number_Of_Vectors => 33,
      Charcode          => 77,
      Left              => -12,
      Right             => 12,
      Top               => -10,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, -10),
         (-4, -6),
         (-7, -2),
         (-8, 1),
         (-8, 3),
         (-7, 5),
         (-5, 6),
         (-3, 6),
         (-1, 5),
         (0, 3),
         Raise_Pen,
         (0, -10),
         (4, -6),
         (7, -2),
         (8, 1),
         (8, 3),
         (7, 5),
         (5, 6),
         (3, 6),
         (1, 5),
         (0, 3),
         Raise_Pen,
         (0, 3),
         (-1, 7),
         (-2, 10),
         Raise_Pen,
         (0, 3),
         (1, 7),
         (2, 10),
         Raise_Pen,
         (-2, 10),
         (2, 10)));
   Glyph_78 : aliased constant Glyph :=
     (Number_Of_Vectors => 26,
      Charcode          => 78,
      Left              => -12,
      Right             => 12,
      Top               => -10,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, -4),
         (-1, -7),
         (-2, -9),
         (-4, -10),
         (-5, -10),
         (-7, -9),
         (-8, -7),
         (-8, -3),
         (-7, 0),
         (-6, 2),
         (-4, 5),
         (0, 10),
         Raise_Pen,
         (0, -4),
         (1, -7),
         (2, -9),
         (4, -10),
         (5, -10),
         (7, -9),
         (8, -7),
         (8, -3),
         (7, 0),
         (6, 2),
         (4, 5),
         (0, 10)));
   Glyph_79 : aliased constant Glyph :=
     (Number_Of_Vectors => 20,
      Charcode          => 79,
      Left              => -12,
      Right             => 12,
      Top               => -11,
      Bottom            => 11,
      Vects             =>
        (Raise_Pen,
         (0, -11),
         (-2, -8),
         (-6, -3),
         (-9, 0),
         Raise_Pen,
         (0, -11),
         (2, -8),
         (6, -3),
         (9, 0),
         Raise_Pen,
         (-9, 0),
         (-6, 3),
         (-2, 8),
         (0, 11),
         Raise_Pen,
         (9, 0),
         (6, 3),
         (2, 8),
         (0, 11)));
   Glyph_80 : aliased constant Glyph :=
     (Number_Of_Vectors => 48,
      Charcode          => 80,
      Left              => -12,
      Right             => 12,
      Top               => -10,
      Bottom            => 10,
      Vects             =>
        (Raise_Pen,
         (0, 2),
         (2, 5),
         (4, 6),
         (6, 6),
         (8, 5),
         (9, 3),
         (9, 1),
         (8, -1),
         (6, -2),
         (4, -2),
         (1, -1),
         Raise_Pen,
         (1, -1),
         (3, -3),
         (4, -5),
         (4, -7),
         (3, -9),
         (1, -10),
         (-1, -10),
         (-3, -9),
         (-4, -7),
         (-4, -5),
         (-3, -3),
         (-1, -1),
         Raise_Pen,
         (-1, -1),
         (-4, -2),
         (-6, -2),
         (-8, -1),
         (-9, 1),
         (-9, 3),
         (-8, 5),
         (-6, 6),
         (-4, 6),
         (-2, 5),
         (0, 2),
         Raise_Pen,
         (0, 2),
         (-1, 7),
         (-2, 10),
         Raise_Pen,
         (0, 2),
         (1, 7),
         (2, 10),
         Raise_Pen,
         (-2, 10),
         (2, 10)));
   Glyph_81 : aliased constant Glyph :=
     (Number_Of_Vectors => 48,
      Charcode          => 81,
      Left              => -9,
      Right             => 9,
      Top               => -39,
      Bottom            => 39,
      Vects             =>
        (Raise_Pen,
         (4, -39),
         (1, -37),
         (-1, -35),
         (-2, -33),
         (-3, -30),
         (-3, -26),
         (-2, -22),
         (2, -14),
         (3, -11),
         (3, -8),
         (2, -5),
         (0, -2),
         Raise_Pen,
         (1, -37),
         (-1, -34),
         (-2, -30),
         (-2, -26),
         (-1, -23),
         (3, -15),
         (4, -11),
         (4, -8),
         (3, -5),
         (0, -2),
         (-4, 0),
         (0, 2),
         (3, 5),
         (4, 8),
         (4, 11),
         (3, 15),
         (-1, 23),
         (-2, 26),
         (-2, 30),
         (-1, 34),
         (1, 37),
         Raise_Pen,
         (0, 2),
         (2, 5),
         (3, 8),
         (3, 11),
         (2, 14),
         (-2, 22),
         (-3, 26),
         (-3, 30),
         (-2, 33),
         (-1, 35),
         (1, 37),
         (4, 39)));
   Glyph_82 : aliased constant Glyph :=
     (Number_Of_Vectors => 48,
      Charcode          => 82,
      Left              => -9,
      Right             => 9,
      Top               => -39,
      Bottom            => 39,
      Vects             =>
        (Raise_Pen,
         (-4, -39),
         (-1, -37),
         (1, -35),
         (2, -33),
         (3, -30),
         (3, -26),
         (2, -22),
         (-2, -14),
         (-3, -11),
         (-3, -8),
         (-2, -5),
         (0, -2),
         Raise_Pen,
         (-1, -37),
         (1, -34),
         (2, -30),
         (2, -26),
         (1, -23),
         (-3, -15),
         (-4, -11),
         (-4, -8),
         (-3, -5),
         (0, -2),
         (4, 0),
         (0, 2),
         (-3, 5),
         (-4, 8),
         (-4, 11),
         (-3, 15),
         (1, 23),
         (2, 26),
         (2, 30),
         (1, 34),
         (-1, 37),
         Raise_Pen,
         (0, 2),
         (-2, 5),
         (-3, 8),
         (-3, 11),
         (-2, 14),
         (2, 22),
         (3, 26),
         (3, 30),
         (2, 33),
         (1, 35),
         (-1, 37),
         (-4, 39)));
   Glyph_83 : aliased constant Glyph :=
     (Number_Of_Vectors => 32,
      Charcode          => 83,
      Left              => -9,
      Right             => 9,
      Top               => -36,
      Bottom            => 36,
      Vects             =>
        (Raise_Pen,
         (4, -36),
         (1, -33),
         (-1, -30),
         (-3, -26),
         (-4, -21),
         (-4, -15),
         (-3, -9),
         (-2, -5),
         (1, 6),
         (2, 10),
         (3, 16),
         (3, 21),
         (2, 26),
         (1, 29),
         (-1, 33),
         Raise_Pen,
         (1, -33),
         (-1, -29),
         (-2, -26),
         (-3, -21),
         (-3, -16),
         (-2, -10),
         (-1, -6),
         (2, 5),
         (3, 9),
         (4, 15),
         (4, 21),
         (3, 26),
         (1, 30),
         (-1, 33),
         (-4, 36)));
   Glyph_84 : aliased constant Glyph :=
     (Number_Of_Vectors => 32,
      Charcode          => 84,
      Left              => -9,
      Right             => 9,
      Top               => -36,
      Bottom            => 36,
      Vects             =>
        (Raise_Pen,
         (-4, -36),
         (-1, -33),
         (1, -30),
         (3, -26),
         (4, -21),
         (4, -15),
         (3, -9),
         (2, -5),
         (-1, 6),
         (-2, 10),
         (-3, 16),
         (-3, 21),
         (-2, 26),
         (-1, 29),
         (1, 33),
         Raise_Pen,
         (-1, -33),
         (1, -29),
         (2, -26),
         (3, -21),
         (3, -16),
         (2, -10),
         (1, -6),
         (-2, 5),
         (-3, 9),
         (-4, 15),
         (-4, 21),
         (-3, 26),
         (-1, 30),
         (1, 33),
         (4, 36)));
   Glyph_85 : aliased constant Glyph :=
     (Number_Of_Vectors => 14,
      Charcode          => 85,
      Left              => -27,
      Right             => 8,
      Top               => -48,
      Bottom            => 32,
      Vects             =>
        (Raise_Pen,
         (-24, 0),
         (-17, 0),
         (0, 29),
         Raise_Pen,
         (-18, 0),
         (-1, 29),
         Raise_Pen,
         (-19, 0),
         (0, 32),
         Raise_Pen,
         (8, -48),
         (4, -8),
         (0, 32)));
   Glyph_86 : aliased constant Glyph :=
     (Number_Of_Vectors => 27,
      Charcode          => 86,
      Left              => -9,
      Right             => 9,
      Top               => -5,
      Bottom            => 13,
      Vects             =>
        (Raise_Pen,
         (2, -5),
         (4, -4),
         (6, -2),
         (6, -3),
         (5, -4),
         (2, -5),
         (-1, -5),
         (-4, -4),
         (-5, -3),
         (-6, -1),
         (-6, 1),
         (-5, 3),
         (-3, 5),
         (1, 8),
         Raise_Pen,
         (-1, -5),
         (-3, -4),
         (-4, -3),
         (-5, -1),
         (-5, 1),
         (-4, 3),
         (1, 8),
         (2, 10),
         (2, 12),
         (1, 13),
         (-1, 13)));
   Glyph_87 : aliased constant Glyph :=
     (Number_Of_Vectors => 45,
      Charcode          => 87,
      Left              => -11,
      Right             => 11,
      Top               => -5,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (-6, -5),
         (-7, -4),
         (-8, -2),
         (-8, 0),
         (-7, 3),
         (-3, 7),
         (-2, 9),
         Raise_Pen,
         (-8, 0),
         (-7, 2),
         (-3, 6),
         (-2, 9),
         (-2, 11),
         (-3, 14),
         (-5, 16),
         (-6, 16),
         (-7, 15),
         (-8, 13),
         (-8, 10),
         (-7, 6),
         (-5, 2),
         (-3, -1),
         (0, -4),
         (2, -5),
         (4, -5),
         (7, -4),
         (8, -2),
         (8, 2),
         (7, 6),
         (5, 8),
         (3, 9),
         (2, 9),
         (1, 8),
         (1, 6),
         (2, 5),
         (3, 6),
         (2, 7),
         Raise_Pen,
         (4, -5),
         (6, -4),
         (7, -2),
         (7, 2),
         (6, 6),
         (5, 8)));
   Glyph_88 : aliased constant Glyph :=
     (Number_Of_Vectors => 69,
      Charcode          => 88,
      Left              => -13,
      Right             => 13,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (7, -11),
         (6, -10),
         (7, -9),
         (8, -10),
         (7, -11),
         (5, -12),
         (2, -12),
         (-1, -11),
         (-3, -9),
         (-4, -7),
         (-5, -4),
         (-6, 0),
         (-8, 9),
         (-9, 13),
         (-10, 15),
         Raise_Pen,
         (2, -12),
         (0, -11),
         (-2, -9),
         (-3, -7),
         (-4, -4),
         (-6, 5),
         (-7, 9),
         (-8, 12),
         (-9, 14),
         (-10, 15),
         (-12, 16),
         (-14, 16),
         (-15, 15),
         (-15, 14),
         (-14, 13),
         (-13, 14),
         (-14, 15),
         Raise_Pen,
         (13, -11),
         (12, -10),
         (13, -9),
         (14, -10),
         (14, -11),
         (13, -12),
         (11, -12),
         (9, -11),
         (8, -10),
         (7, -8),
         (6, -5),
         (3, 9),
         (2, 13),
         (1, 15),
         Raise_Pen,
         (11, -12),
         (9, -10),
         (8, -8),
         (7, -4),
         (5, 5),
         (4, 9),
         (3, 12),
         (2, 14),
         (1, 15),
         (-1, 16),
         (-3, 16),
         (-4, 15),
         (-4, 14),
         (-3, 13),
         (-2, 14),
         (-3, 15),
         Raise_Pen,
         (-9, -5),
         (12, -5)));
   Glyph_89 : aliased constant Glyph :=
     (Number_Of_Vectors => 52,
      Charcode          => 89,
      Left              => -12,
      Right             => 12,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (9, -11),
         (8, -10),
         (9, -9),
         (10, -10),
         (9, -11),
         (6, -12),
         (3, -12),
         (0, -11),
         (-2, -9),
         (-3, -7),
         (-4, -4),
         (-5, 0),
         (-7, 9),
         (-8, 13),
         (-9, 15),
         Raise_Pen,
         (3, -12),
         (1, -11),
         (-1, -9),
         (-2, -7),
         (-3, -4),
         (-5, 5),
         (-6, 9),
         (-7, 12),
         (-8, 14),
         (-9, 15),
         (-11, 16),
         (-13, 16),
         (-14, 15),
         (-14, 14),
         (-13, 13),
         (-12, 14),
         (-13, 15),
         Raise_Pen,
         (7, -5),
         (5, 2),
         (4, 6),
         (4, 8),
         (5, 9),
         (8, 9),
         (10, 7),
         (11, 5),
         Raise_Pen,
         (8, -5),
         (6, 2),
         (5, 6),
         (5, 8),
         (6, 9),
         Raise_Pen,
         (-8, -5),
         (8, -5)));
   Glyph_90 : aliased constant Glyph :=
     (Number_Of_Vectors => 54,
      Charcode          => 90,
      Left              => -12,
      Right             => 12,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (7, -11),
         (6, -10),
         (7, -9),
         (8, -10),
         (8, -11),
         (6, -12),
         Raise_Pen,
         (10, -12),
         (3, -12),
         (0, -11),
         (-2, -9),
         (-3, -7),
         (-4, -4),
         (-5, 0),
         (-7, 9),
         (-8, 13),
         (-9, 15),
         Raise_Pen,
         (3, -12),
         (1, -11),
         (-1, -9),
         (-2, -7),
         (-3, -4),
         (-5, 5),
         (-6, 9),
         (-7, 12),
         (-8, 14),
         (-9, 15),
         (-11, 16),
         (-13, 16),
         (-14, 15),
         (-14, 14),
         (-13, 13),
         (-12, 14),
         (-13, 15),
         Raise_Pen,
         (9, -12),
         (5, 2),
         (4, 6),
         (4, 8),
         (5, 9),
         (8, 9),
         (10, 7),
         (11, 5),
         Raise_Pen,
         (10, -12),
         (6, 2),
         (5, 6),
         (5, 8),
         (6, 9),
         Raise_Pen,
         (-8, -5),
         (7, -5)));
   Glyph_91 : aliased constant Glyph :=
     (Number_Of_Vectors => 86,
      Charcode          => 91,
      Left              => -18,
      Right             => 17,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (2, -11),
         (1, -10),
         (2, -9),
         (3, -10),
         (2, -11),
         (0, -12),
         (-3, -12),
         (-6, -11),
         (-8, -9),
         (-9, -7),
         (-10, -4),
         (-11, 0),
         (-13, 9),
         (-14, 13),
         (-15, 15),
         Raise_Pen,
         (-3, -12),
         (-5, -11),
         (-7, -9),
         (-8, -7),
         (-9, -4),
         (-11, 5),
         (-12, 9),
         (-13, 12),
         (-14, 14),
         (-15, 15),
         (-17, 16),
         (-19, 16),
         (-20, 15),
         (-20, 14),
         (-19, 13),
         (-18, 14),
         (-19, 15),
         Raise_Pen,
         (14, -11),
         (13, -10),
         (14, -9),
         (15, -10),
         (14, -11),
         (11, -12),
         (8, -12),
         (5, -11),
         (3, -9),
         (2, -7),
         (1, -4),
         (0, 0),
         (-2, 9),
         (-3, 13),
         (-4, 15),
         Raise_Pen,
         (8, -12),
         (6, -11),
         (4, -9),
         (3, -7),
         (2, -4),
         (0, 5),
         (-1, 9),
         (-2, 12),
         (-3, 14),
         (-4, 15),
         (-6, 16),
         (-8, 16),
         (-9, 15),
         (-9, 14),
         (-8, 13),
         (-7, 14),
         (-8, 15),
         Raise_Pen,
         (12, -5),
         (10, 2),
         (9, 6),
         (9, 8),
         (10, 9),
         (13, 9),
         (15, 7),
         (16, 5),
         Raise_Pen,
         (13, -5),
         (11, 2),
         (10, 6),
         (10, 8),
         (11, 9),
         Raise_Pen,
         (-14, -5),
         (13, -5)));
   Glyph_92 : aliased constant Glyph :=
     (Number_Of_Vectors => 88,
      Charcode          => 92,
      Left              => -18,
      Right             => 17,
      Top               => -12,
      Bottom            => 16,
      Vects             =>
        (Raise_Pen,
         (2, -11),
         (1, -10),
         (2, -9),
         (3, -10),
         (2, -11),
         (0, -12),
         (-3, -12),
         (-6, -11),
         (-8, -9),
         (-9, -7),
         (-10, -4),
         (-11, 0),
         (-13, 9),
         (-14, 13),
         (-15, 15),
         Raise_Pen,
         (-3, -12),
         (-5, -11),
         (-7, -9),
         (-8, -7),
         (-9, -4),
         (-11, 5),
         (-12, 9),
         (-13, 12),
         (-14, 14),
         (-15, 15),
         (-17, 16),
         (-19, 16),
         (-20, 15),
         (-20, 14),
         (-19, 13),
         (-18, 14),
         (-19, 15),
         Raise_Pen,
         (12, -11),
         (11, -10),
         (12, -9),
         (13, -10),
         (13, -11),
         (11, -12),
         Raise_Pen,
         (15, -12),
         (8, -12),
         (5, -11),
         (3, -9),
         (2, -7),
         (1, -4),
         (0, 0),
         (-2, 9),
         (-3, 13),
         (-4, 15),
         Raise_Pen,
         (8, -12),
         (6, -11),
         (4, -9),
         (3, -7),
         (2, -4),
         (0, 5),
         (-1, 9),
         (-2, 12),
         (-3, 14),
         (-4, 15),
         (-6, 16),
         (-8, 16),
         (-9, 15),
         (-9, 14),
         (-8, 13),
         (-7, 14),
         (-8, 15),
         Raise_Pen,
         (14, -12),
         (10, 2),
         (9, 6),
         (9, 8),
         (10, 9),
         (13, 9),
         (15, 7),
         (16, 5),
         Raise_Pen,
         (15, -12),
         (11, 2),
         (10, 6),
         (10, 8),
         (11, 9),
         Raise_Pen,
         (-14, -5),
         (12, -5)));
   Glyph_93 : aliased constant Glyph :=
     (Number_Of_Vectors => 20,
      Charcode          => 93,
      Left              => -6,
      Right             => 7,
      Top               => -5,
      Bottom            => 9,
      Vects             =>
        (Raise_Pen,
         (-5, -1),
         (-4, -3),
         (-2, -5),
         (1, -5),
         (2, -4),
         (2, -1),
         (0, 5),
         (0, 8),
         (1, 9),
         Raise_Pen,
         (0, -5),
         (1, -4),
         (1, -1),
         (-1, 5),
         (-1, 8),
         (0, 9),
         (3, 9),
         (5, 7),
         (6, 5)));
   Glyph_94 : aliased constant Glyph :=
     (Number_Of_Vectors => 22,
      Charcode          => 94,
      Left              => -6,
      Right             => 6,
      Top               => -6,
      Bottom            => 5,
      Vects             =>
        (Raise_Pen,
         (0, -6),
         (-4, 5),
         (6, -2),
         (-6, -2),
         (4, 5),
         (0, -6),
         Raise_Pen,
         (0, 0),
         (0, -6),
         Raise_Pen,
         (0, 0),
         (-6, -2),
         Raise_Pen,
         (0, 0),
         (-4, 5),
         Raise_Pen,
         (0, 0),
         (4, 5),
         Raise_Pen,
         (0, 0),
         (6, -2)));
   Glyph_95 : aliased constant Glyph :=
     (Number_Of_Vectors => 24,
      Charcode          => 95,
      Left              => -12,
      Right             => 12,
      Top               => -3,
      Bottom            => 3,
      Vects             =>
        (Raise_Pen,
         (-9, 3),
         (-9, 1),
         (-8, -2),
         (-6, -3),
         (-4, -3),
         (-2, -2),
         (2, 1),
         (4, 2),
         (6, 2),
         (8, 1),
         (9, -1),
         Raise_Pen,
         (-9, 1),
         (-8, -1),
         (-6, -2),
         (-4, -2),
         (-2, -1),
         (2, 2),
         (4, 3),
         (6, 3),
         (8, 2),
         (9, -1),
         (9, -3)));

   Font_D : aliased constant Font_Def :=
     (Number_Of_Glyphs => 96,
      Glyphs           =>
        (Glyph_0'Access,
         Glyph_1'Access,
         Glyph_2'Access,
         Glyph_3'Access,
         Glyph_4'Access,
         Glyph_5'Access,
         Glyph_6'Access,
         Glyph_7'Access,
         Glyph_8'Access,
         Glyph_9'Access,
         Glyph_10'Access,
         Glyph_11'Access,
         Glyph_12'Access,
         Glyph_13'Access,
         Glyph_14'Access,
         Glyph_15'Access,
         Glyph_16'Access,
         Glyph_17'Access,
         Glyph_18'Access,
         Glyph_19'Access,
         Glyph_20'Access,
         Glyph_21'Access,
         Glyph_22'Access,
         Glyph_23'Access,
         Glyph_24'Access,
         Glyph_25'Access,
         Glyph_26'Access,
         Glyph_27'Access,
         Glyph_28'Access,
         Glyph_29'Access,
         Glyph_30'Access,
         Glyph_31'Access,
         Glyph_32'Access,
         Glyph_33'Access,
         Glyph_34'Access,
         Glyph_35'Access,
         Glyph_36'Access,
         Glyph_37'Access,
         Glyph_38'Access,
         Glyph_39'Access,
         Glyph_40'Access,
         Glyph_41'Access,
         Glyph_42'Access,
         Glyph_43'Access,
         Glyph_44'Access,
         Glyph_45'Access,
         Glyph_46'Access,
         Glyph_47'Access,
         Glyph_48'Access,
         Glyph_49'Access,
         Glyph_50'Access,
         Glyph_51'Access,
         Glyph_52'Access,
         Glyph_53'Access,
         Glyph_54'Access,
         Glyph_55'Access,
         Glyph_56'Access,
         Glyph_57'Access,
         Glyph_58'Access,
         Glyph_59'Access,
         Glyph_60'Access,
         Glyph_61'Access,
         Glyph_62'Access,
         Glyph_63'Access,
         Glyph_64'Access,
         Glyph_65'Access,
         Glyph_66'Access,
         Glyph_67'Access,
         Glyph_68'Access,
         Glyph_69'Access,
         Glyph_70'Access,
         Glyph_71'Access,
         Glyph_72'Access,
         Glyph_73'Access,
         Glyph_74'Access,
         Glyph_75'Access,
         Glyph_76'Access,
         Glyph_77'Access,
         Glyph_78'Access,
         Glyph_79'Access,
         Glyph_80'Access,
         Glyph_81'Access,
         Glyph_82'Access,
         Glyph_83'Access,
         Glyph_84'Access,
         Glyph_85'Access,
         Glyph_86'Access,
         Glyph_87'Access,
         Glyph_88'Access,
         Glyph_89'Access,
         Glyph_90'Access,
         Glyph_91'Access,
         Glyph_92'Access,
         Glyph_93'Access,
         Glyph_94'Access,
         Glyph_95'Access));
   Font : constant Font_Access := Font_D'Access;
end Hershey_Fonts.Symbolic;
